import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { CategoryDataProvider } from "@/context/CategoryDataContext";
import "./globals.css";
import "../styles/variables.css";
import "../styles/ReactToastify.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // Import default styles

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider defaultTheme="system" enableSystem>
          <ToastContainer
          // position="bottom-right"
          // autoClose={3000}
          // hideProgressBar={false}
          // newestOnTop={false}
          // closeOnClick
          // rtl={false}
          // pauseOnFocusLoss
          // draggable
          // pauseOnHover
          />
          <AuthProvider>
            <CategoryDataProvider>
              <div className="gradient-container">
                <div className="gradient-image"></div>
              </div>
              <Navbar />
              <main className="flex-grow-1">{children}</main>
              <Footer />
            </CategoryDataProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
